web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Security;

namespace web.Controllers
{
    public class HomeController : Controller
    {
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Roles.Reportes, (int)Habilitado.SI)]
        public ActionResult Index()
        {
            ViewBag.logExito = TempData["logExito"] as string;
            return View();
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Roles.Reportes, (int)Habilitado.SI)]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Roles.Reportes, (int)Habilitado.SI)]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Roles.Reportes, (int)Habilitado.SI)]
        public ActionResult Inventario()
        {
            return View();
        }
    }
}

web/Controllers/ProcesosController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using web.Utils;
using Web.Security;

namespace web.Controllers
{
    public class ProcesosController : Controller
    {
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Habilitado.SI)]
        public ActionResult Entrada()
        {
            ViewBag.IDPRODUCTO = listaProductos();
            ViewBag.IDPROVEDOR = listaProveedores();
            ViewBag.IDSUCURSAL = listaSucursales();
            ViewBag.IDTIPOMOVIMIENTOENTRADA = listaTipoMovimientoEntrada();
            return View();
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Habilitado.SI)]
        public ActionResult Salida()
        {
            ViewBag.IDPRODUCTO = listaProductos();
            ViewBag.IDPROVEDOR = listaProveedores();
            ViewBag.IDSUCURSAL = listaSucursales();
            ViewBag.IDTIPOMOVIMIENTOSALIDA = listaTipoMovimientoSalida();
            return View();
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Habilitado.SI)]
        private SelectList listaProveedores(int idProveedor = 0)
        {
            IServiceProveedor _ServiceProveedor = new ServiceProveedor();
            IEnumerable<Proveedor> listaProveedores = _ServiceProveedor.GetProveedores();
            return new SelectList(listaProveedores, "idProveedor", "nombre", idProveedor);
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Habilitado.SI)]
        private SelectList listaSucursales(int idSucursal = 0)
        {
            IServiceProducto _ServiceSucursal = new ServiceProducto();
            IEnumerable<Sucursal> listaSucursales = _ServiceSucursal.GetSucursales();
            return new SelectList(listaSucursales, "idSucursal", "descripcion", idSucursal);
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Habilitado.SI)]
        private SelectList listaProductos(int idProducto = 0)
        {
            IServiceProducto _ServiceProducto = new ServiceProducto();
            IEnumerable<Producto> listaProductos = _ServiceProducto.GetProductos();
            return new SelectList(listaProductos, "idProducto", "nombre", idProducto);
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Habilitado.SI)]
        private SelectList listaTipoMovimientoEntrada(int idTipo = 0)
        {
            int tipo = 1;
            IServiceMovimiento _ServiceMovimiento = new ServiceMovimiento();
            IEnumerable<TipoMovimiento> listaMovimientos = _ServiceMovimiento.GetTipoMovimiento(tipo);
            return new SelectList(listaMovimientos, "idConcepto", "descripcion", idTipo);
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Habilitado.SI)]
        private SelectList listaTipoMovimientoSalida(int idTipo = 0)
        {
            int tipo = 2;
            IServiceMovimiento _ServiceMovimiento = new ServiceMovimiento();
            IEnumerable<TipoMovimiento> listaMovimientos = _ServiceMovimiento.GetTipoMovimiento(tipo);
            return new SelectList(listaMovimientos, "idConcepto", "descripcion", idTipo);
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Habilitado.SI)]
        public ActionResult Compra()
        {
            ViewBag.IDPRODUCTO = listaProductos();
            ViewBag.IDPROVEDOR = listaProveedores();
            ViewBag.IDSUCURSAL = listaSucursales();
            ViewBag.IDTIPOMOVIMIENTOENTRADA = listaTipoMovimientoEntrada();
            return View();
        }
        [HttpPost]
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Habilitado.SI)]
        public JsonResult crearMovimiento(Movimiento objMovimiento)
        {
            IServiceMovimiento _ServiceMovimiento = new ServiceMovimiento();
            Movimiento m = new Movimiento();
            Movimiento cargarViewBag = new Movimiento();
            m.idTipoMovimiento = (int)objMovimiento.idTipoMovimiento;
            m.idConcepto = (int)objMovimiento.idConcepto;
            m.fecha = objMovimiento.fecha;
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["CONFIRMADO"] = "true";
                    Movimiento oMovimientoI = _ServiceMovimiento.guardarMovimiento(m);
                    cargarViewBag = _ServiceMovimiento.UltimoMovimiento();
                    ViewBag.ULTIMOMOVIMIENTO = cargarViewBag;
                }
                else
                {
                    // Valida Errores si Javascript está deshabilitado
                    Util.ValidateErrors(this);
                }
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Redirect"] = "Compra";
                TempData["Redirect-Action"] = "Compra";
                // Redireccion a la captura del Error
                return new JsonResult { Data = new { idTipoMovimiento = 0, idConcepto = 0, fecha = "" } };
            }
            return new JsonResult { Data = new { idTipoMovimiento = 0, idConcepto = 0, fecha = "" } };
        }
        [CustomAuthorize((int)Roles.Administrador, (int)Roles.Bodeguero, (int)Habilitado.SI)]
        public ActionResult GuardarMovimiento(DetMovimiento detMovimiento, int numMov)
        {
            IServiceMovimiento _ServiceMovimiento = new ServiceMovimiento();
            DetMovimiento d = new DetMovimiento();

            d.idMovimiento = numMov;
            d.idProducto = detMovimiento.idProducto;
            d.idProveedor = detMovimiento.idProveedor;
            d.idSucursal = detMovimiento.idSucursal;
            d.idUsuario = detMovimiento.idUsuario;
            d.cantidad = detMovimiento.cantidad;
            d.observacion = detMovimiento.observacion;

            try
            {
                if (ModelState.IsValid)
                {
                    TempData["CONFIRMADO"] = "true";
                    DetMovimiento oDetMovimientoI = _ServiceMovimiento.guardarDetMovimiento(d);
                }
                else
                {
                    // Valida Errores si Javascript está deshabilitado
                    Util.ValidateErrors(this);
                    return View("Compra", detMovimiento);
                }

                return RedirectToAction("Compra");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData["Redirect"] = "mantenimientoProductos";
                TempData["Redirect-Action"] = "mantenimientoProductos";
                // Redireccion a la captura del Error
                return RedirectToAction("mantenimientoProductos", "Producto");
            }
        }
    }
}

web/Views/Home/About.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Acerca de</title>
    <link rel="stylesheet" href="~/Content/about.css" type="text/css" />
</head>
<body>
    <main>
        <header>
            <ul class="nav">
                <li>@Html.ActionLink("Inicio", "Index")</li>
                <li id="usuario">
                    @{
                        string nombre = "Perfil";
                        int idUsuario = 207870114;
                        Infraestructure.Models.Usuario oUsuario;
                        //Validar si existe en la sesión
                        if (Session["User"] != null)
                        {
                            oUsuario = (Infraestructure.Models.Usuario)Session["User"];
                            if (oUsuario != null)
                            {
                                nombre = $"{oUsuario.nombre}";
                                idUsuario = oUsuario.idUsuario;
                            }
                        }
                    }
                    <a data-toggle="dropdown" href="#" role="button">@nombre</a>
                    <ul>
                        @if (Session["User"] != null)
                        {
                            <li>@Html.ActionLink("" + idUsuario, "Index")</li>

                        }
                        @if (Session["User"] == null)
                        {
                            @Html.ActionLink("Ingresar", "Index", "Usuario", null, new { @style = "font-size: 20px;" })
                        }
                        else
                        {

                            <li>@Html.ActionLink("Cerrar sesión", "Logout", "Usuario", null, new { @class = "dropdown-item " })</li>
                        }
                    </ul>
                </li>                
            </ul>
        </header>
        <section id="empresa">
            <h1>¿Quienes somos?</h1>
            <p>
                DeLaHuerta es un emprendimiento familiar que trabaja todos los días
                para acercarte productos frescos y de primera calidad. Nos dedicamos
                exclusivamente a esto y tenemos la experiencia necesaria que nos
                permite seleccionar diariamente los mejores productos de la temporada
                para tenerlos a su disposición. Disponemos de una amplia variedad de
                productos lo que asegura que siempre encontrará una alternativa
                adecuada para su familia.
            </p>
            <h2>Misión</h2>
            <p>
                Nuestra misión es satisfacer las necesidades de todos nuestros
                clientes así como también de nuestros trabajadores, con el objetivo de
                maximizar la eficiencia y optimizar la rentabilidad a través de
                nuestra diferenciación en calidad de producto, servicio y precio.
            </p>
            <h2>Visión</h2>
            <p>
                Nuestra visión es conseguir la confianza de nuestros clientes a través
                de comercialización sobre productos de calidad, a partir de la cual,
                afianzar un crecimiento progresivo y sostenido en el mercado nacional,
                consolidando nuestra posición como empresa de referencia en el sector
                con una imagen corporativa propia y diferenciada de sus competidores.
                DeLaHuerta trabaja para conseguir la máxima calidad, un catálogo de
                productos diversificado y el mejor servicio al precio más competitivo.
            </p>
        </section>
        <section id="autor">
            <h1>Autor</h1>
            <h2 class="text">Nombre</h2>
            <p class="text2">Richard Josué Conejo Berrocal.</p>
            <h2 class="text">Cedula</h2>
            <p class="text2">207870114</p>
        </section>
        <section id="direccion">
            <h1>Contácto</h1>
            <p class="text2">San Pedro de Poás, Alajuela.</p>
            <h2 class="text">Correo</h2>
            <p class="text2" id="email">conejorichard1998@gmail.com</p>
            <h2 class="text">Teléfono</h2>
            <p class="text2" id="telefono">88058073</p>
        </section>
    </main>
</body>
</html>

web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DeLaHuerta</title>
    <link rel="stylesheet" href="~/Content/home.css" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body onload="logExito()">
    <main>
        <header>
            <ul class="nav">
                <li>@Html.ActionLink("Inicio", "Index")</li>
                <li>
                    @Html.ActionLink("Mantenimiento", "Index")
                    <ul>
                        <li>@Html.ActionLink("Productos", "listadoProducto", "Producto")</li>
                        <li>@Html.ActionLink("Usuarios", "listadoUsuarios", "Usuario")</li>
                        <li>@Html.ActionLink("Proveedor", "listadoProveedores", "Proveedor")</li>
                    </ul>
                </li>
                <li>
                    <a href="">Procesos</a>
                    <ul>
                        <li>@Html.ActionLink("Entrada", "Entrada", "Procesos")</li>
                        <li>@Html.ActionLink("Salida", "Salida", "Procesos")</li>
                    </ul>
                </li>
                <li>
                    <a href="">Reportes</a>
                    <ul>
                        <li><a href="">Informe entradas</a></li>
                        <li><a href="">Informe salidas</a></li>
                        <li><a href="">Informe productos</a></li>
                    </ul>
                </li>
                <li>@Html.ActionLink("Inventario", "Inventario")</li>
                <li>@Html.ActionLink("Acerca de", "About")</li>
                <li id="usuario">
                    @{
                        string nombre = "Perfil";
                        int idUsuario = 207870114;
                        Infraestructure.Models.Usuario oUsuario;
                        //Validar si existe en la sesión
                        if (Session["User"] != null)
                        {
                            oUsuario = (Infraestructure.Models.Usuario)Session["User"];
                            if (oUsuario != null)
                            {
                                nombre = $"{oUsuario.nombre}";
                                idUsuario = oUsuario.idUsuario;
                            }
                        }
                    }
                    <a data-toggle="dropdown" href="#" role="button">@nombre</a>
                    <ul>
                        @if (Session["User"] != null)
                        {
                            <li>@Html.ActionLink("" + idUsuario, "Index")</li>

                        }
                        @if (Session["User"] == null)
                        {
                            @Html.ActionLink("Ingresar", "Index", "Usuario", null, new { @style = "font-size: 20px;" })
                        }
                        else
                        {
                            <li>@Html.ActionLink("Cerrar sesión", "Logout", "Usuario", null, new { @logOut=1, @class = "dropdown-item " })</li>
                        }
                    </ul>
                </li>
            </ul>
        </header>
        <section>
            <img src="~/img/DLH2.jpg" style="width: 300px;">
            <div class="container" id="container">
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                        <li data-target="#myCarousel" data-slide-to="3"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        <div class="item active">
                            <img src="~/img/variedad.png" alt="a" style="width:100%; height:250px;">
                        </div>

                        <div class="item">
                            <img src="~/img/banano.png" alt="a" style="width:100%; height:250px;">
                        </div>

                        <div class="item">
                            <img src="~/img/pera.png" alt="a" style="width:100%; height:250px;">
                        </div>
                        <div class="item">
                            <img src="~/img/suc.png" alt="a" style="width:100%; height:250px;">
                        </div>
                    </div>

                    <!-- Left and right controls -->
                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

            <article>
                <p>
                    Estamos más que felices de darle la bienvenida en nuestro cálido y amigable gestor de inventariado en línea sobre frutas, verduras, pan y lácteos 100% frescos.
                    Deseamos que nos conozca más de cerca, porque no somos nuevos en la industria de la alimentación en Costa Rica.
                    DeLaHuerta una empresa especializada en ofrecer un servicio integral de alimentación con más de 20 años de experiencia.
                    A través de los años hemos implementando técnicas y herramientas que nos han permitido llegar a miles de personas con nuestra calidad en el servicio y alimentación.
                    Es por ello que hemos trasladado la administración de nuestro productos por medio de la tecnología para así aumentar nuestra efiencia como empresa, todo con el fin de ofrecer
                    producto fresco y de primera mano.
                </p>
            </article>
        </section>
    </main>
    <script>
        function logExito() {
            let strValor = "@((string)ViewBag.logExito)";
            if (strValor !== null && strValor !== '') {
                swal({
                    title: "¡Enhorabuena!",
                    text: "¡Has iniciado sesión con éxito!",
                    type: "success",
                    button: "OK",
                });
            }
        }
    </script>
</body>
</html>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

web/Views/Home/Inventario.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Inventario</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/Content/inventario.css" type="text/css">
</head>
<body>

    <main>
        <header>
            <ul class="nav">
                <li>@Html.ActionLink("Inicio", "index")</li>
                <li id="usuario">
                    @{
                        string nombre = "Perfil";
                        int idUsuario = 207870114;
                        Infraestructure.Models.Usuario oUsuario;
                        //Validar si existe en la sesión
                        if (Session["User"] != null)
                        {
                            oUsuario = (Infraestructure.Models.Usuario)Session["User"];
                            if (oUsuario != null)
                            {
                                nombre = $"{oUsuario.nombre}";
                                idUsuario = oUsuario.idUsuario;
                            }
                        }
                    }
                    <a data-toggle="dropdown" href="#" role="button">@nombre</a>
                    <ul>
                        @if (Session["User"] != null)
                        {
                            <li>@Html.ActionLink("" + idUsuario, "Index")</li>

                        }
                        @if (Session["User"] == null)
                        {
                            @Html.ActionLink("Ingresar", "Index", "Usuario", null, new { @style = "font-size: 20px;" })
                        }
                        else
                        {

                            <li>@Html.ActionLink("Cerrar sesión", "Logout", "Usuario", null, new { @class = "dropdown-item " })</li>
                        }
                    </ul>
                </li>
            </ul>
        </header>
        <section>
            <center>
                <div id="titulo">
                    <h5 style="font-size: 1px; padding-bottom: 3%;">.</h5>
                    <h1>Inventariado DeLaHuerta</h1>
                    <p>Acá encontrarás todo lo relevante y referente sobre nuestros productos de primera mano.</p>
                </div>
            </center>
            <!-- Productos -->
                <div id="divProd" class="table">                    
                    <table class="table table-bordered table-striped mb-0">
                        <thead>
                            <tr style="background-color:#238926; color: #fff;">
                                <th scope="col"><center>#</center></th>
                                <th style="width:20%;" scope="col">Inventario de:</th>
                                <th scope="col">Descripción</th>
                                <th scope="col"><center>Enlace</center></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">1</th>
                                <td>Productos</td>
                                <td>Acá encontrarás todo lo referente a nuestros productos</td>
                                <td><center><button type="button" onclick="location.href = '@Url.Action("Producto", "Producto")'">Vamos</button></center></td>
                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>Proveedores</td>
                                <td>Acá podrás observar todo lo relacionado con nuestros proveedores</td>
                                <td><center><button type="button" onclick="location.href = '@Url.Action("Proveedores", "Proveedor")'">Vamos</button></center></td>
                            </tr>
                            <tr>
                                <th scope="row">3</th>
                                <td>Movimientos</td>
                                <td>Acá hallarás todos nuestros movimientos de inventario</td>
                                <td><center><button type="button" onclick="location.href = '@Url.Action("Movimientos", "Movimientos")'">Vamos</button></center></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
        </section>
    </main>
</body>
</html>